/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemafacturacionmuebles;

import java.awt.Color;
import javax.swing.JOptionPane;

/**
 *
 * @author Kevin
 */
public class cambioClave extends javax.swing.JInternalFrame {

    /**
     * Creates new form cambioClave
     */
    USER u;
    CONEXION conect;
    boolean hCC; //Se puede cambiar clave
    public cambioClave(USER us) {
        initComponents();
        u=us;
        conect = new CONEXION();
        this.hCC=false;
    }

    private void checkDatos(char[] oldP, char[] p1, char[] p2){
        String oldPass = new String(oldP);
        String pass1 = new String(p1);
        String pass2 = new String(p2); 
        if(!this.u.getClave().equals(oldPass)){
            this.msgCC.setForeground(Color.RED);
            this.msgCC.setText("*Clave ingresada no coincide con la actual!.");
            this.hCC=false;
        } else{
            if(!pass1.equals("") && !pass2.equals("") && pass1.equals(pass2)){
                this.msgCC.setForeground(Color.GREEN);
                this.msgCC.setText("Listo para ingreso de usuario.");
                this.hCC=true;
            } else if(pass1.equals("") && pass2.equals("")){
                this.msgCC.setForeground(Color.RED);
                this.msgCC.setText("*La nueva clave no puede estar vacía!.");
                this.hCC=false;
            } else{
                this.msgCC.setForeground(Color.RED);
                this.msgCC.setText("*Ambas contraseñas deben de coincidir.");
                this.hCC=false;
            }
        
        }
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtClaveNew = new javax.swing.JPasswordField();
        txtClaveNew2 = new javax.swing.JPasswordField();
        btnCambio = new javax.swing.JButton();
        txtClaveOld = new javax.swing.JPasswordField();
        msgCC = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setClosable(true);
        setTitle("OPCIONES ADMINISTRATIVAS");
        setMinimumSize(new java.awt.Dimension(350, 270));
        setPreferredSize(new java.awt.Dimension(350, 270));

        jLabel10.setText("Clave nueva:");

        jLabel11.setText("Repetir clave:");

        txtClaveNew.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClaveNewFocusLost(evt);
            }
        });

        txtClaveNew2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClaveNew2FocusLost(evt);
            }
        });

        btnCambio.setText("Cambiar clave");
        btnCambio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCambioMouseClicked(evt);
            }
        });
        btnCambio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCambioActionPerformed(evt);
            }
        });

        txtClaveOld.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtClaveOldFocusLost(evt);
            }
        });

        msgCC.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 204, 204)));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel8.setText("Cambio de clave");

        jLabel9.setText("Clave actual:");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(65, 65, 65)
                        .addComponent(jLabel8))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(msgCC, javax.swing.GroupLayout.PREFERRED_SIZE, 257, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(81, 81, 81)
                                .addComponent(btnCambio)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel10)
                                .addComponent(jLabel9)
                                .addComponent(jLabel11))
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txtClaveNew)
                                .addComponent(txtClaveNew2)
                                .addComponent(txtClaveOld, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(45, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel8)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtClaveOld, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtClaveNew, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtClaveNew2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(msgCC, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCambio)
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void txtClaveNewFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClaveNewFocusLost
        // TODO add your handling code here:
        this.checkDatos(this.txtClaveOld.getPassword(), this.txtClaveNew.getPassword(), this.txtClaveNew2.getPassword());
    }//GEN-LAST:event_txtClaveNewFocusLost

    private void txtClaveNew2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClaveNew2FocusLost
        // TODO add your handling code here:
        this.checkDatos(this.txtClaveOld.getPassword(), this.txtClaveNew.getPassword(), this.txtClaveNew2.getPassword());
    }//GEN-LAST:event_txtClaveNew2FocusLost

    private void btnCambioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCambioMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCambioMouseClicked

    private void btnCambioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCambioActionPerformed
        // TODO add your handling code here:
        //Aqui va el codigo para cambio de clave
        if(hCC){
            
            String clave = new String(this.txtClaveNew.getPassword());
            this.u.setClave(clave);
            conect.CONECTAR();
            conect.EJECUTAR("UPDATE usuarios SET clave='"+clave+"' WHERE id_usuario='"+this.u.getUser()+"';");
            conect.CERRAR();
            this.txtClaveNew.setText("");
            this.txtClaveNew2.setText("");
            this.txtClaveOld.setText("");
            JOptionPane.showMessageDialog(null, "Clave cambiada con éxito!");
            this.hCC=false;
        } else{
            JOptionPane.showMessageDialog(null,"Datos inválidos. Imposible cambiar clave!");
        }
    }//GEN-LAST:event_btnCambioActionPerformed

    private void txtClaveOldFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtClaveOldFocusLost
        // TODO add your handling code here:
        this.checkDatos(this.txtClaveOld.getPassword(), this.txtClaveNew.getPassword(), this.txtClaveNew2.getPassword());
    }//GEN-LAST:event_txtClaveOldFocusLost


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCambio;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel msgCC;
    private javax.swing.JPasswordField txtClaveNew;
    private javax.swing.JPasswordField txtClaveNew2;
    private javax.swing.JPasswordField txtClaveOld;
    // End of variables declaration//GEN-END:variables
}
